import type { ChipDef, Point, StageDef } from "./types";

export const BOARD = { w: 1280, h: 600 };

export const CHIPS: ChipDef[] = [
  {
    id: "camera",
    name: "Camera In",
    part: "RCA / frame grabber",
    x: 36,
    y: 28,
    w: 108,
    h: 44,
    kind: "port",
    blurb:
      "Analog video arrives here. The NeXTcube had no built-in camera; a frame grabber or NeXTdimension board digitized the signal before the DSP ever saw it.",
    specs: [
      { label: "Connector", value: "RCA composite" },
      { label: "Sample", value: "8-bit luma" },
      { label: "Rate", value: "frame trigger" },
    ],
  },
  {
    id: "monitor",
    name: "Monitor Out",
    part: "13W3 MegaPixel",
    x: 1136,
    y: 28,
    w: 108,
    h: 44,
    kind: "port",
    blurb:
      "The MegaPixel Display is 1120×832, 2-bit grayscale, 68 Hz. A custom 13W3 connector carries analog video plus display ID pins.",
    specs: [
      { label: "Resolution", value: "1120 × 832" },
      { label: "Depth", value: "2-bit gray" },
      { label: "Refresh", value: "68 Hz" },
    ],
  },
  {
    id: "dsp",
    name: "DSP56001",
    part: "Motorola 24-bit DSP · 25 MHz",
    x: 36,
    y: 92,
    w: 168,
    h: 124,
    kind: "dsp",
    blurb:
      "The 56001 is a 24-bit fixed-point DSP with a Harvard architecture. On the cube it owns real-time audio and can preprocess video before the 68040 ever wakes.",
    specs: [
      { label: "Clock", value: "25 MHz" },
      { label: "SRAM", value: "24 KB (to 96 KB)" },
      { label: "Width", value: "24-bit data" },
      { label: "Peak", value: "12.5 MIPS" },
    ],
    internals: [
      { label: "X / Y mem", value: "Separate data spaces" },
      { label: "P mem", value: "Program RAM" },
      { label: "ALU", value: "24-bit + 56-bit acc" },
    ],
  },
  {
    id: "cpu",
    name: "MC68040",
    part: "MCM56824AFN35 · 25 MHz",
    x: 228,
    y: 76,
    w: 300,
    h: 156,
    kind: "cpu",
    blurb:
      "Motorola’s 68040 folds the integer core, FPU, and paged MMU onto one 1.2 million-transistor die. NeXTcube 040 systems clock it at 25 MHz with 8 KB of on-chip cache.",
    specs: [
      { label: "Clock", value: "25 MHz" },
      { label: "Process", value: "0.8 µm CMOS" },
      { label: "Cache", value: "4 KB I + 4 KB D" },
      { label: "Bus", value: "32-bit multiplexed" },
    ],
    internals: [
      { label: "IU", value: "6-stage integer pipe" },
      { label: "FPU", value: "IEEE 754 extended" },
      { label: "PMMU", value: "4-entry ATC / 4 KB pages" },
      { label: "Caches", value: "4-way, write-through D" },
    ],
  },
  {
    id: "ram",
    name: "Main RAM",
    part: "SIMM banks · up to 64 MB",
    x: 552,
    y: 92,
    w: 196,
    h: 124,
    kind: "ram",
    blurb:
      "Parity DRAM in 72-pin SIMMs. The 68040 MMU maps this into 4 KB pages. Frame data lands here before the CPU filter runs, then is copied out to VRAM.",
    specs: [
      { label: "Capacity", value: "8–64 MB" },
      { label: "Width", value: "32-bit + parity" },
      { label: "Page", value: "4 KB" },
    ],
  },
  {
    id: "fb",
    name: "Frame Buffer",
    part: "Dual-port VRAM · 1120×832",
    x: 772,
    y: 84,
    w: 216,
    h: 140,
    kind: "fb",
    blurb:
      "2-bit grayscale VRAM scanned out independently of the CPU. 1120×832×2 bits is 232,960 bytes — a full frame is a handful of NeXTbus bursts.",
    specs: [
      { label: "Pixels", value: "1120 × 832" },
      { label: "Depth", value: "2 bits (4 grays)" },
      { label: "Size", value: "227.5 KB" },
      { label: "Port", value: "CPU + CRT" },
    ],
  },
  {
    id: "disp",
    name: "Display Ctrl",
    part: "MegaPixel timing ASIC",
    x: 1012,
    y: 92,
    w: 168,
    h: 124,
    kind: "io",
    blurb:
      "A custom video timing generator drives horizontal/vertical sync and serializes 2-bit pixels to the analog drive of the MegaPixel monitor.",
    specs: [
      { label: "Pixel clock", value: "~64 MHz" },
      { label: "Sync", value: "68 Hz vertical" },
      { label: "Out", value: "13W3 analog" },
    ],
  },
  {
    id: "bus",
    name: "NeXTbus",
    part: "25 MHz · 32-bit multiplexed",
    x: 36,
    y: 248,
    w: 1208,
    h: 40,
    kind: "bus",
    blurb:
      "The spine of the cube. Address and data share the same 32 pins; bursts can theoretically hit 100 MB/s. Every DMA, CPU write, and NIC transfer rides this highway.",
    specs: [
      { label: "Clock", value: "25 MHz" },
      { label: "Width", value: "32-bit mux" },
      { label: "Burst", value: "up to 100 MB/s" },
      { label: "Slots", value: "2 expansion" },
    ],
  },
  {
    id: "eth",
    name: "Ethernet",
    part: "Am7990 LANCE + Am7992 SIA",
    x: 36,
    y: 312,
    w: 220,
    h: 112,
    kind: "nic",
    blurb:
      "AMD’s LANCE (Local Area Network Controller for Ethernet) plus Serial Interface Adapter. 10 Mbps IEEE 802.3, DMA-capable, both 10BASE-T and thinnet.",
    specs: [
      { label: "MAC", value: "Am7990 LANCE" },
      { label: "PHY", value: "Am7992 SIA" },
      { label: "Speed", value: "10 Mbps" },
      { label: "OUI", value: "08:00:07" },
    ],
  },
  {
    id: "scsi",
    name: "SCSI",
    part: "NCR 53C90",
    x: 276,
    y: 320,
    w: 160,
    h: 96,
    kind: "io",
    blurb: "SCSI-1 host adapter for the internal hard disk, magneto-optical, and CD-ROM. DMA onto NeXTbus.",
    specs: [
      { label: "Chip", value: "NCR 53C90" },
      { label: "Bus", value: "SCSI-1, 5 MB/s" },
    ],
  },
  {
    id: "audio",
    name: "Audio codec",
    part: "16-bit stereo via DSP",
    x: 456,
    y: 320,
    w: 160,
    h: 96,
    kind: "io",
    blurb:
      "Microphone and line out ride the 56001. Later cubes added a 16-bit codec; early machines used µ-law through the DSP.",
    specs: [
      { label: "Sample", value: "8–44.1 kHz" },
      { label: "Path", value: "DSP56001" },
    ],
  },
  {
    id: "rom",
    name: "Boot ROM",
    part: "PROM / 4 MB firmware",
    x: 636,
    y: 320,
    w: 160,
    h: 96,
    kind: "io",
    blurb: "Contains the boot monitor, POST, and enough of the kernel to find a disk. The cube can netboot from here.",
    specs: [
      { label: "Contents", value: "Monitor + POST" },
      { label: "Netboot", value: "BOOTP / NFS" },
    ],
  },
  {
    id: "dma",
    name: "DMA",
    part: "4-channel controller",
    x: 816,
    y: 320,
    w: 160,
    h: 96,
    kind: "io",
    blurb: "Offloads burst copies between SCSI, Ethernet, DSP SRAM, and main memory so the 68040 can keep computing.",
    specs: [
      { label: "Channels", value: "4" },
      { label: "Width", value: "32-bit" },
    ],
  },
  {
    id: "io",
    name: "I/O ASIC",
    part: "Keyboard · mouse · serial",
    x: 996,
    y: 320,
    w: 184,
    h: 96,
    kind: "io",
    blurb: "A gate array that folds the keyboard/mouse port, two serial ports, and floppy control into one package.",
    specs: [
      { label: "Kbd", value: "NeXT mini-DIN" },
      { label: "Serial", value: "RS-232 × 2" },
    ],
  },
  {
    id: "rj45",
    name: "RJ45",
    part: "10BASE-T",
    x: 36,
    y: 448,
    w: 80,
    h: 40,
    kind: "port",
    blurb: "Twisted-pair Ethernet. The cube shipped with both RJ45 and BNC so it could join either office plant.",
    specs: [{ label: "PHY", value: "10BASE-T" }],
  },
  {
    id: "bnc",
    name: "BNC",
    part: "10BASE2 thinnet",
    x: 128,
    y: 448,
    w: 72,
    h: 40,
    kind: "port",
    blurb: "50 Ω coaxial Ethernet. A T-connector and terminator hang off this jack on a classic thinnet segment.",
    specs: [{ label: "PHY", value: "10BASE2" }],
  },
  {
    id: "kbd",
    name: "Keyboard",
    part: "NeXT mini-DIN",
    x: 276,
    y: 448,
    w: 160,
    h: 40,
    kind: "port",
    blurb: "The cube’s keyboard and mouse share a proprietary mini-DIN — not Apple ADB, despite the similar look.",
    specs: [{ label: "Devices", value: "Kbd + mouse" }],
  },
  {
    id: "serial",
    name: "Serial",
    part: "RS-232 / DB-9",
    x: 456,
    y: 448,
    w: 160,
    h: 40,
    kind: "port",
    blurb: "Two serial ports for printers, modems, and lab gear. The original laser printer often hung off here.",
    specs: [{ label: "Rate", value: "up to 38.4 kbaud" }],
  },
  {
    id: "scsi-port",
    name: "SCSI out",
    part: "External 50-pin",
    x: 636,
    y: 448,
    w: 160,
    h: 40,
    kind: "port",
    blurb: "External SCSI daisy-chain for magneto-optical drives and scanners.",
    specs: [{ label: "Connector", value: "Centronics 50" }],
  },
  {
    id: "exp",
    name: "Expansion",
    part: "2 × NeXTbus slots",
    x: 816,
    y: 448,
    w: 160,
    h: 40,
    kind: "port",
    blurb: "NeXTdimension (color + video) and other boards plug in here, riding the same 32-bit multiplexed bus.",
    specs: [{ label: "Slots", value: "2" }],
  },
  {
    id: "pwr",
    name: "Power",
    part: "±5 V · ±12 V",
    x: 996,
    y: 448,
    w: 184,
    h: 40,
    kind: "pwr",
    blurb: "Linear regulation from the cube’s internal supply. A lithium cell keeps PRAM and the DS1287 RTC alive.",
    specs: [
      { label: "Rails", value: "+5, −5, +12, −12" },
      { label: "RTC", value: "DS1287" },
    ],
  },
];

export const CHIP_MAP: Record<string, ChipDef> = Object.fromEntries(CHIPS.map((c) => [c.id, c]));

export function chipCenter(id: string): Point {
  const c = CHIP_MAP[id];
  if (!c) return { x: 0, y: 0 };
  return { x: c.x + c.w / 2, y: c.y + c.h / 2 };
}

function via(id: string, y: number): Point {
  const c = chipCenter(id);
  return { x: c.x, y };
}

const BUS_Y = 268;

export const PATH_IN: Point[] = [
  chipCenter("camera"),
  { x: chipCenter("camera").x, y: chipCenter("dsp").y },
  chipCenter("dsp"),
  via("dsp", BUS_Y),
  via("ram", BUS_Y),
  chipCenter("ram"),
  via("ram", BUS_Y),
  via("cpu", BUS_Y),
  chipCenter("cpu"),
  via("cpu", BUS_Y),
  via("fb", BUS_Y),
  chipCenter("fb"),
  chipCenter("disp"),
  chipCenter("monitor"),
];

export const PATH_OUT: Point[] = [
  chipCenter("fb"),
  via("fb", BUS_Y),
  via("cpu", BUS_Y),
  chipCenter("cpu"),
  via("cpu", BUS_Y),
  via("eth", BUS_Y),
  chipCenter("eth"),
  chipCenter("rj45"),
];

export const PIXEL_STAGES: StageDef[] = [
  {
    id: "camera",
    at: 0,
    chip: "camera",
    title: "Frame grabber",
    detail: "Analog composite is sampled. A full raster waits on the grabber’s line buffer.",
    format: "8-bit luma · ~900 KB",
    bytes: 900_000,
  },
  {
    id: "dsp",
    at: 0.1,
    chip: "dsp",
    title: "DSP56001 preprocess",
    detail: "24-bit FIR low-pass, chroma drop, scale toward 1120×832. SRAM holds a strip at a time.",
    format: "24-bit DSP words",
    bytes: 480_000,
  },
  {
    id: "bus_ram",
    at: 0.22,
    chip: "bus",
    title: "NeXTbus → DRAM",
    detail: "DMA master: 32-bit multiplexed bursts into main memory. Address then data on the same pins.",
    format: "Burst 16 × 32-bit",
    bytes: 372_736,
  },
  {
    id: "ram",
    at: 0.32,
    chip: "ram",
    title: "Resident in RAM",
    detail: "The MMU maps the frame into 4 KB pages. Parity DRAM now holds the working copy.",
    format: "32-bit aligned gray",
    bytes: 372_736,
  },
  {
    id: "cpu",
    at: 0.42,
    chip: "cpu",
    title: "68040 + FPU filter",
    detail: "Integer unit walks pixels; FPU accumulates kernel weights. Write-through D-cache absorbs stores.",
    format: "Filtered gray",
    bytes: 372_736,
  },
  {
    id: "cache",
    at: 0.55,
    chip: "cpu",
    title: "Cache traffic",
    detail: "4 KB I-cache holds the inner loop. D-cache hits keep the pipeline from stalling on each pixel.",
    format: "4-way lines · 16 B",
    bytes: 372_736,
  },
  {
    id: "bus_fb",
    at: 0.64,
    chip: "bus",
    title: "NeXTbus → VRAM",
    detail: "CPU writes quantized 2-bit packed pixels. Four pixels per byte. Burst to dual-port VRAM.",
    format: "2 bpp packed",
    bytes: 232_960,
  },
  {
    id: "fb",
    at: 0.75,
    chip: "fb",
    title: "Frame buffer latch",
    detail: "VRAM now holds 227.5 KB. The CRT port can scan while the CPU port still writes.",
    format: "1120×832 × 2-bit",
    bytes: 232_960,
  },
  {
    id: "disp",
    at: 0.85,
    chip: "disp",
    title: "MegaPixel controller",
    detail: "Timing ASIC serializes pixels, raises HSYNC/VSYNC, drives the analog guns through 13W3.",
    format: "Pixel clock ~64 MHz",
    bytes: 232_960,
  },
  {
    id: "monitor",
    at: 0.94,
    chip: "monitor",
    title: "MegaPixel Display",
    detail: "Phosphor. 68 Hz. Four gray levels. The cube’s entire visual world is this raster.",
    format: "1120×832 @ 68 Hz",
    bytes: 232_960,
  },
];

export const SHARE_STAGES: StageDef[] = [
  {
    id: "fb_read",
    at: 0,
    chip: "fb",
    title: "Capture scanout",
    detail: "Read the live frame buffer — the same bits the monitor is drawing.",
    format: "2 bpp VRAM",
    bytes: 232_960,
  },
  {
    id: "compress",
    at: 0.12,
    chip: "cpu",
    title: "Delta encode",
    detail: "CPU + DSP emit only tiles that changed. First frame is a keyframe; later frames shrink hard.",
    format: "Tile delta",
    bytes: 80_000,
  },
  {
    id: "bus_nic",
    at: 0.26,
    chip: "bus",
    title: "DMA to LANCE",
    detail: "Compressed payload is chained into LANCE transmit descriptors in main memory, then DMA’d.",
    format: "Descriptor ring",
    bytes: 80_000,
  },
  {
    id: "packetize",
    at: 0.36,
    chip: "eth",
    title: "Ethernet II wrap",
    detail: "Dest 08:00:07:r3:m0:te, EtherType 0x0800, IPv4, TCP/5900. 1400-byte payloads.",
    format: "1514 B frames",
    bytes: 1514,
  },
  {
    id: "transmit",
    at: 0.48,
    chip: "rj45",
    title: "10BASE-T PHY",
    detail: "Manchester on twisted pair. 10 Mbps peak. Collisions would jam and backoff; we have a switch.",
    format: "10 Mbps",
    bytes: 1514,
  },
  {
    id: "wire",
    at: 0.58,
    chip: "rj45",
    title: "On the wire",
    detail: "Latency and loss are yours to set. Drops trigger TCP retransmit; the 68040 handles ACKs.",
    format: "IPv4 / TCP",
    bytes: 1514,
  },
  {
    id: "recv",
    at: 0.72,
    chip: "eth",
    title: "Remote NIC",
    detail: "Far-end LANCE DMA’s frames into RAM. Sequence numbers reassemble the tile stream.",
    format: "TCP stream",
    bytes: 1514,
  },
  {
    id: "remote",
    at: 0.88,
    chip: "monitor",
    title: "Remote viewer",
    detail: "Tiles decompress onto a remote framebuffer. Missing tiles wait on retransmit.",
    format: "2 bpp reconstructed",
    bytes: 232_960,
  },
];

export const NEXT_OUI = "08:00:07";
export const SRC_MAC = "08:00:07:c4:b3:01";
export const DST_MAC = "08:00:07:11:22:33";
