import type { ChipId, CpuUnit } from "./chips";
import { nativeFrameBytes, nativeIngestBytes, NATIVE } from "./image";

export type JourneyKind = "pixel" | "share";

export interface Step {
  id: string;
  title: string;
  kicker: string;
  body: string;
  format: string;
  size: string;
  modern: string;
  chips: ChipId[];
  units?: CpuUnit[];
  path: ChipId[];
  cpu: number;
  dsp: number;
  bus: number;
  net: number;
  durationMs: number;
  reveal?: number;
  packets?: "build" | "send" | "ack";
}

const ingest = nativeIngestBytes();
const fb = nativeFrameBytes();

export const PIXEL_STEPS: Step[] = [
  {
    id: "photons",
    title: "Photons, then voltages",
    kicker: "Sensor",
    body: "Light from the bench hits a simulated CCD/CMOS. Each photosite integrates charge in proportion to luminance. There is still no digital number — only analog voltages on a column bus. A Cube never had a camera of its own; this is the ADC we hang off the DSP port so the rest of the journey can be real silicon.",
    format: "Analog · column voltages · ~1 V full scale",
    size: `${NATIVE.w} × ${NATIVE.h} photosites`,
    modern: "The ISP + sensor in a laptop lid, or getUserMedia before the first compressed packet.",
    chips: ["camera"],
    path: ["camera"],
    cpu: 0,
    dsp: 4,
    bus: 0,
    net: 0,
    durationMs: 900,
  },
  {
    id: "adc",
    title: "ADC on the DSP port",
    kicker: "Ingest",
    body: "An 8-bit analog-to-digital converter samples each photosite. The DSP56001's host/SSI port latches 24-bit words with the gray sample in the low 8 bits — the same port NeXT used for 16-bit 44.1 kHz audio. From here the frame has a name the kernel can DMA.",
    format: "Unsigned 8-bit gray packed in 24-bit DSP words",
    size: `${ingest.toLocaleString()} bytes ingest (${NATIVE.w}×${NATIVE.h}×8-bit)`,
    modern: "A MIPI CSI-2 packet from the sensor, unpacked by the SoC's camera block.",
    chips: ["camera", "dsp"],
    path: ["camera", "dsp"],
    cpu: 2,
    dsp: 35,
    bus: 4,
    net: 0,
    durationMs: 1100,
  },
  {
    id: "dsp-kernel",
    title: "56001 walks the raster",
    kicker: "DSP",
    body: "The DSP56001 runs a tiny kernel from P-memory: optional low-pass, gain, and a 2× box downsample toward the working buffer. Multiply-accumulate is free here; the 68040 would spend tens of milliseconds on the same FIR. State and the packed tile live in the MCM56824 SRAM — 8K × 24, 24 KB, private to the DSP.",
    format: "24-bit MAC accumulators · X/Y memory · 512-word blocks",
    size: `24 KB SRAM window · ${Math.round(ingest / 1024)} KB still in flight`,
    modern: "A camera ISP pipeline (denoise, demosaic, tone map) or a shader compute pass.",
    chips: ["dsp", "dspRam"],
    units: ["iu"],
    path: ["dsp", "dspRam"],
    cpu: 6,
    dsp: 88,
    bus: 8,
    net: 0,
    durationMs: 1400,
  },
  {
    id: "dma",
    title: "ICP takes the bus",
    kicker: "DMA",
    body: "The I/O ASIC raises an interrupt: buffer ready. The 68040 writes a DMA descriptor — source (DSP host port), destination (a physical SIMM page), length — and the Integrated Channel Processor becomes bus master. The CPU can go back to sleep. Burst writes on the 32-bit 25 MHz NeXTbus are the 100 MB/s number on the data sheet.",
    format: "NeXTbus burst · 32-bit multiplexed address/data",
    size: `${ingest.toLocaleString()} bytes across the bus in ~10 ms theoretical`,
    modern: "An IOMMU-mapped DMA from the camera block into a vm_page the GPU/CPU can both see.",
    chips: ["dsp", "icp", "bus", "ram", "ioasic"],
    units: ["mmu"],
    path: ["dspRam", "dsp", "icp", "bus", "ram"],
    cpu: 18,
    dsp: 40,
    bus: 92,
    net: 0,
    durationMs: 1300,
  },
  {
    id: "cpu-convert",
    title: "68040 posterises the page",
    kicker: "CPU",
    body: "Window Server wants 2 bits per pixel. The integer unit walks the 8-bit buffer, the PMMU translates the virtual mapping, the 4 KB I-cache holds the inner loop, the 4 KB write-back D-cache is a sliding window (a frame does not fit), and the on-chip FPU optionally applies a 3×3 kernel. Output is four gray levels — the entire visual vocabulary of the MegaPixel.",
    format: "8-bit gray → 2-bit packed (4 pixels / byte)",
    size: `${ingest.toLocaleString()} B in · ${fb.toLocaleString()} B out`,
    modern: "A GPU compute shader or vImage / libyuv conversion. Colour would die here on a stock Cube.",
    chips: ["ram", "cpu", "memctl"],
    units: ["iu", "fpu", "mmu", "icache", "dcache"],
    path: ["ram", "cpu", "memctl"],
    cpu: 94,
    dsp: 8,
    bus: 55,
    net: 0,
    durationMs: 1600,
  },
  {
    id: "fb-write",
    title: "Write the MegaPixel RAM",
    kicker: "Framebuffer",
    body: "The packed 2-bit raster is copied into the dedicated 256 KB display DRAM. This is a different array from the SIMMs — scanout can read it while the 68040 is already thinking about something else. 1120×832×2 bits = 232,960 bytes. There is no blit hardware; this copy *is* the graphics card.",
    format: "2 bpp packed · 256 KB display DRAM",
    size: `${fb.toLocaleString()} bytes (${NATIVE.w}×${NATIVE.h}×2-bit)`,
    modern: "A GPU present / flip to the scanout buffer, often through a compositor (WindowServer, DWM, Weston).",
    chips: ["cpu", "bus", "framebuffer", "vlsi"],
    units: ["dcache", "iu"],
    path: ["cpu", "bus", "framebuffer"],
    cpu: 48,
    dsp: 0,
    bus: 80,
    net: 0,
    durationMs: 1200,
    reveal: 0.55,
  },
  {
    id: "scanout",
    title: "68 Hz to phosphor",
    kicker: "CRT",
    body: "The VLSI display companion walks the framebuffer independently, serialises 2-bit pixels, and a tiny DAC emits four analog voltages plus sync down the NeXT display cable. The MegaPixel's electron beam paints 1120×832, 68 times a second. A byte that left the camera as charge is now a glowing patch of phosphor.",
    format: "Analog gray levels · H/V sync · 68 Hz",
    size: `${NATIVE.w}×${NATIVE.h} @ ${NATIVE.refreshHz} Hz`,
    modern: "DisplayPort/HDMI packets, or an eDP link to a laptop panel. Still just scanout.",
    chips: ["framebuffer", "vlsi", "displayPort", "monitor"],
    path: ["framebuffer", "vlsi", "displayPort", "monitor"],
    cpu: 6,
    dsp: 0,
    bus: 12,
    net: 0,
    durationMs: 1400,
    reveal: 1,
  },
];

export const SHARE_STEPS: Step[] = [
  {
    id: "capture",
    title: "Read the live framebuffer",
    kicker: "Capture",
    body: "Desktop sharing begins by stealing what the CRT is already showing. The ICP DMA-reads the 256 KB display DRAM into a SIMM buffer. This is the 1991 version of DXGI Desktop Duplication or ScreenCaptureKit: copy the scanout memory, don't hook the window server.",
    format: "2 bpp framebuffer snapshot",
    size: `${fb.toLocaleString()} bytes captured`,
    modern: "DXGI Desktop Duplication, ScreenCaptureKit, or getDisplayMedia in the browser.",
    chips: ["framebuffer", "icp", "bus", "ram"],
    units: ["mmu"],
    path: ["monitor", "displayPort", "framebuffer", "icp", "ram"],
    cpu: 22,
    dsp: 4,
    bus: 78,
    net: 0,
    durationMs: 1100,
  },
  {
    id: "delta",
    title: "XOR delta + RLE",
    kicker: "Compress",
    body: "A full 227 KB frame at 10 Mb/s is ~180 ms — too slow for a cursor. The 68040 XORs this frame against the last one (idle desktops compress to almost nothing) and run-length encodes the residual. The DSP56001 can take the RLE inner loop if the integer unit is busy with TCP. This is the ancestor of damage regions in VNC and of 'only send dirty tiles' in every screen-share app.",
    format: "XOR residual · RLE · 16 horizontal strips",
    size: `~${Math.round(fb / 8).toLocaleString()} bytes typical (8:1 on a still desktop)`,
    modern: "Damage regions + H.264/AV1. Zoom/Teams do this on a GPU encoder; we do it in 25 MHz software.",
    chips: ["ram", "cpu", "dsp", "dspRam"],
    units: ["iu", "icache", "dcache", "fpu"],
    path: ["ram", "cpu", "dsp"],
    cpu: 90,
    dsp: 55,
    bus: 40,
    net: 0,
    durationMs: 1500,
  },
  {
    id: "stack",
    title: "TCP/IP on the 68040",
    kicker: "Stack",
    body: "NeXTSTEP's BSD stack wraps each strip: TCP (port 5900, the number VNC later made famous), IPv4, Ethernet. The CPU computes the checksum. There is no TSO, no checksum offload, no TLS. Sequence numbers and a sliding window are the only congestion control — and you can starve them with the latency slider.",
    format: "TCP · IPv4 · Ethernet II · OUI 08:00:07",
    size: "MSS ≈ 1460 B · 16 strips → 16–24 frames",
    modern: "A userspace stack (QUIC, SRTP, WebRTC) plus kernel TCP. Encryption would live here now.",
    chips: ["cpu", "ram"],
    units: ["iu", "icache", "dcache"],
    path: ["cpu", "ram"],
    cpu: 70,
    dsp: 10,
    bus: 28,
    net: 0,
    durationMs: 1100,
    packets: "build",
  },
  {
    id: "mac",
    title: "82586 builds the wire frame",
    kicker: "MAC",
    body: "The Intel 82586 is a coprocessor. The kernel leaves a command block and a descriptor ring in RAM; the 82586 DMAs the payload, prepends dest/src MAC (NeXT's OUI is 08:00:07), ethertype 0x0800, and appends a 32-bit FCS. CSMA/CD waits for a quiet 10 Mb/s channel. The 68040 does not touch a single Manchester bit.",
    format: "Preamble 7×AA + SB · dest · src · type · payload · FCS",
    size: "64–1518 B on the wire per frame",
    modern: "A NIC's Tx ring, with TSO/GSO stitching 64 KB of TCP into many frames in hardware.",
    chips: ["ram", "nic", "icp"],
    units: ["mmu"],
    path: ["ram", "icp", "nic"],
    cpu: 25,
    dsp: 0,
    bus: 72,
    net: 15,
    durationMs: 1200,
    packets: "build",
  },
  {
    id: "wire",
    title: "10 Mb/s onto copper",
    kicker: "PHY",
    body: "The transceiver Manchester-encodes the bitstream and drives either the RJ-45 magnetics (10BASE-T) or the BNC (10BASE2). Theoretical peak is 1.25 MB/s. Bandwidth, latency, and loss sliders now decide whether a strip arrives, arrives late, or dies and must be born again.",
    format: "Manchester · 10 Mb/s half-duplex · CSMA/CD",
    size: "Link capacity 1.25 MB/s",
    modern: "A 10 GbE PHY with FEC, or a Wi-Fi 6 radio — still bits as voltages, plus a lot more retry.",
    chips: ["nic", "phy", "rj45", "bnc"],
    path: ["nic", "phy", "rj45"],
    cpu: 12,
    dsp: 0,
    bus: 20,
    net: 85,
    durationMs: 1600,
    packets: "send",
  },
  {
    id: "remote",
    title: "Reassemble, ACK, paint",
    kicker: "Peer",
    body: "The peer 82586 CRCs each frame. Good ones land in RAM; the TCP stack ACKs; a dropped strip is retried (watch the CPU spike). XOR + RLE reverse into a 2-bit raster and the remote MegaPixel paints it. That last hop — packet to phosphor on someone else's desk — is all a screen-share app has ever been.",
    format: "TCP ACK · RLE reverse · 2 bpp blit",
    size: "One MegaPixel, delayed by RTT + loss",
    modern: "Jitter buffer + decoder + present, with NACK/PLI when a Zoom tile freezes.",
    chips: ["rj45", "remote", "cpu"],
    units: ["iu"],
    path: ["rj45", "remote"],
    cpu: 40,
    dsp: 8,
    bus: 30,
    net: 60,
    durationMs: 1600,
    packets: "ack",
  },
];

export function stepsFor(kind: JourneyKind) {
  return kind === "pixel" ? PIXEL_STEPS : SHARE_STEPS;
}
